# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Qt Designer\qttest\wmi_usb.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import win32com.client
from PyQt5.QtCore import QThread




class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setMinimumSize(QtCore.QSize(159, 138))
        MainWindow.setMaximumSize(QtCore.QSize(159, 138))
        self.centralwidget = QtWidgets.QWidget(MainWindow) 
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 40, 120, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(26)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 159, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "USB_Count"))
        self.label.setText(_translate("MainWindow", f"<html><head/><body><p align=\"center\">0</p></body></html>"))


# def __init__(self):
#     self.setFixedSize(self.width(),self.height())
#     self.SetupUi(self)

if __name__ == '__main__':
    import sys
    app=QtWidgets.QApplication(sys.argv)
    ui=Ui_MainWindow()
    mainWindow=QtWidgets.QMainWindow()
    mbox=QtWidgets.QMessageBox(mainWindow)

    ui.setupUi(mainWindow)
    mainWindow.show()

    count=0
    wmi = win32com.client.GetObject("winmgmts:")
    query_insert = "SELECT * FROM __InstanceCreationEvent WITHIN 2 WHERE TargetInstance ISA 'Win32_USBHub'"
    query_remove = "SELECT * FROM __InstanceDeletionEvent WITHIN 2 WHERE TargetInstance ISA 'Win32_USBHub'"
    usb_insert_watcher = wmi.ExecNotificationQuery(query_insert)
    usb_remove_watcher = wmi.ExecNotificationQuery(query_remove)

    sys.exit(app.exec())



    while True:

        insert_event = usb_insert_watcher.NextEvent()
        # on_usb_insert(insert_event.TargetInstance)
        count+=1
        ui.retranslateUi(mainWindow)
        print(count)



